/* ===========================================================================
   ADVANCE POS SYSTEM (AdvPOS) -- PostgreSQL schema
   Tenant modelled: VIZO Pakistan -- mobile-accessories distribution.
   Derived from the frontend at github.com/AmmarKamran2005/advpos-frontend
   ---------------------------------------------------------------------------
   RULES HONOURED

     * PostgreSQL only.
     * 1NF / 2NF / 3NF. Repeating groups (barcodes, carriers, permissions,
       collection allocations) are broken out into child tables. Transitive
       dependencies (city -> province, account -> type -> group) are removed.
     * No CREATE TYPE ... AS ENUM anywhere. Every closed value set is a
       lookup table joined by a parent -> child foreign key.
     * Table names in PascalCase, therefore double-quoted. Column names are
       lower snake_case so everyday SQL stays unquoted and readable.
     * No stored procedures, no triggers, no functions.
     * Primary and foreign keys only. No CREATE INDEX. UNIQUE appears only
       where a duplicate would be a real bug: e-mail, party code, SKU,
       document numbers.
     * Money is DECIMAL(14,2), percentages DECIMAL(5,2). No FLOAT anywhere.
     * ON UPDATE CASCADE on every foreign key. ON DELETE CASCADE where the
       child is owned by the parent, ON DELETE SET NULL where the reference
       is optional. No foreign key ever blocks a delete.
     * Document status is a lookup table plus a current-status FK on the
       document. Status HISTORY is deliberately not here -- it is delivered
       separately in 04_status_history.sql.

   FILE ORDER:  01_schema.sql  ->  02_seed.sql  ->  03_sequence_reset.sql
   =========================================================================== */


/* ===========================================================================
   SECTION 1 -- LOOKUP TABLES (these stand in for every enum in the frontend)
   =========================================================================== */

CREATE TABLE "SeverityLevel" (
    severity_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity_key     VARCHAR(20)  NOT NULL UNIQUE,
    severity_name    VARCHAR(40)  NOT NULL
);

CREATE TABLE "Role" (
    role_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key         VARCHAR(30)  NOT NULL UNIQUE,
    role_name        VARCHAR(60)  NOT NULL,
    description      VARCHAR(200) NOT NULL,
    home_path        VARCHAR(100) NOT NULL DEFAULT '/dashboard',
    is_staff_role    BOOLEAN      NOT NULL DEFAULT TRUE,
    /* Staff sign in, so their address is mandatory and unique. Customers and
       suppliers are opened by the Super Admin off a phone call and very often
       have no e-mail at all. */
    requires_email   BOOLEAN      NOT NULL DEFAULT TRUE,
    is_system        BOOLEAN      NOT NULL DEFAULT TRUE,
    /* Target of the composite FK on "User" that enforces the e-mail rule
       without a trigger. */
    CONSTRAINT uq_role_email_rule UNIQUE (role_id, requires_email)
);

CREATE TABLE "Permission" (
    permission_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key   VARCHAR(40)  NOT NULL UNIQUE,
    label            VARCHAR(80)  NOT NULL,
    group_name       VARCHAR(40)  NOT NULL
);

CREATE TABLE "Province" (
    province_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province_name    VARCHAR(60)  NOT NULL UNIQUE
);

CREATE TABLE "LocationKind" (
    kind_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind_key         VARCHAR(20)  NOT NULL UNIQUE,
    kind_name        VARCHAR(40)  NOT NULL
);

CREATE TABLE "PartyCategory" (
    category_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key     VARCHAR(20)  NOT NULL UNIQUE,
    category_name    VARCHAR(40)  NOT NULL
);

CREATE TABLE "CreditHoldPolicy" (
    policy_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_key       VARCHAR(10)  NOT NULL UNIQUE,
    policy_name      VARCHAR(40)  NOT NULL,
    description      VARCHAR(140) NOT NULL
);

/* One payment vocabulary serving orders, vouchers, expenses, field
   collections and refunds. Four near-identical lists would be normalisation
   for its own sake. */
CREATE TABLE "PaymentMethod" (
    method_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_key       VARCHAR(20)  NOT NULL UNIQUE,
    method_name      VARCHAR(40)  NOT NULL,
    method_kind      VARCHAR(20)  NOT NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE "OrderStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL,
    sort_order       INT          NOT NULL
);

CREATE TABLE "InvoiceStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

CREATE TABLE "ReturnStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

CREATE TABLE "PurchaseOrderStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(25)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

/* Shared by every document that is simply raised, checked and posted:
   goods receipts, journal entries, vouchers, expenses, stock corrections. */
CREATE TABLE "PostingStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

CREATE TABLE "TransferStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(25)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

/* One vocabulary for a consignment: the courier portal's own states plus the
   two the business added -- AWAITING (we sent it, nobody has confirmed) and
   IN_TRANSIT (somebody checked, it is still moving). */
CREATE TABLE "DeliveryStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(25)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL,
    is_open          BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE "ClaimStage" (
    stage_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_key        VARCHAR(20)  NOT NULL UNIQUE,
    stage_name       VARCHAR(40)  NOT NULL,
    is_open          BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE "ClaimReason" (
    reason_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_key       VARCHAR(20)  NOT NULL UNIQUE,
    reason_name      VARCHAR(60)  NOT NULL,
    usually_accepted BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE "ClaimOutcome" (
    outcome_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_key      VARCHAR(20)  NOT NULL UNIQUE,
    outcome_name     VARCHAR(60)  NOT NULL
);

CREATE TABLE "CollectionStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);

CREATE TABLE "AdjustmentReason" (
    reason_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_key       VARCHAR(25)  NOT NULL UNIQUE,
    reason_name      VARCHAR(60)  NOT NULL
);

/* Why a piece moved. Which WAY it moved is the sign on
   "StockMovement".quantity -- a direction column here would be a second copy
   of that fact, and a stock correction can go either way in any case. */
CREATE TABLE "MovementType" (
    movement_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_key         VARCHAR(25)  NOT NULL UNIQUE,
    type_name        VARCHAR(40)  NOT NULL
);

CREATE TABLE "ReturnCondition" (
    condition_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_key    VARCHAR(20)  NOT NULL UNIQUE,
    condition_name   VARCHAR(40)  NOT NULL,
    is_resalable     BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE "VisitOutcome" (
    outcome_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_key      VARCHAR(25)  NOT NULL UNIQUE,
    outcome_name     VARCHAR(40)  NOT NULL
);

CREATE TABLE "VoucherType" (
    voucher_type_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code        VARCHAR(4)   NOT NULL UNIQUE,
    type_name        VARCHAR(40)  NOT NULL,
    /* TRUE = money coming in, FALSE = money going out. */
    is_receipt       BOOLEAN      NOT NULL
);

CREATE TABLE "JournalEntryType" (
    entry_type_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_key         VARCHAR(20)  NOT NULL UNIQUE,
    type_name        VARCHAR(40)  NOT NULL
);

CREATE TABLE "BackupType" (
    backup_type_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_key         VARCHAR(20)  NOT NULL UNIQUE,
    type_name        VARCHAR(40)  NOT NULL
);

CREATE TABLE "BackupStatus" (
    status_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_key       VARCHAR(20)  NOT NULL UNIQUE,
    status_name      VARCHAR(40)  NOT NULL
);


/* ===========================================================================
   SECTION 2 -- COMPANY, GEOGRAPHY AND STOCK LOCATIONS
   =========================================================================== */

/* city -> province is a transitive dependency if both sit on "Party", so the
   city is its own entity and the party points at it. */
CREATE TABLE "City" (
    city_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name        VARCHAR(80)  NOT NULL,
    province_id      INT          NOT NULL,
    CONSTRAINT uq_city_in_province UNIQUE (city_name, province_id),
    CONSTRAINT fk_city_province FOREIGN KEY (province_id)
        REFERENCES "Province" (province_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "Company" (
    company_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name           VARCHAR(120) NOT NULL,
    legal_name             VARCHAR(150) NOT NULL,
    address_line           VARCHAR(200) NOT NULL,
    city_id                INT          NOT NULL,
    country                VARCHAR(60)  NOT NULL DEFAULT 'Pakistan',
    phone                  VARCHAR(30)  NOT NULL,
    email                  VARCHAR(120) NOT NULL UNIQUE,
    ntn                    VARCHAR(20)  NOT NULL UNIQUE,
    strn                   VARCHAR(30)  NOT NULL UNIQUE,
    /* 10 = the client's financial year runs October to September. */
    fiscal_year_start_month SMALLINT    NOT NULL DEFAULT 10
        CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
    currency_code          CHAR(3)      NOT NULL DEFAULT 'PKR',
    currency_symbol        VARCHAR(6)   NOT NULL DEFAULT 'PKR',
    foreign_rate           DECIMAL(12,4) NOT NULL DEFAULT 1.0000
        CHECK (foreign_rate > 0),
    CONSTRAINT fk_company_city FOREIGN KEY (city_id)
        REFERENCES "City" (city_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Every behavioural switch from the Setup screens: stock policy, sales
   policy, delivery policy, claim policy. Key/value keeps four single-row
   tables out of the schema. */
CREATE TABLE "AppSetting" (
    setting_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_group    VARCHAR(30)  NOT NULL,
    setting_key      VARCHAR(60)  NOT NULL UNIQUE,
    setting_value    VARCHAR(200) NOT NULL,
    description      VARCHAR(200) NOT NULL
);

/* One flat list of places stock can sit. Replaces the old branch/warehouse
   split -- the business runs a single premises. */
CREATE TABLE "Location" (
    location_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code           VARCHAR(10)  NOT NULL UNIQUE,
    location_name           VARCHAR(80)  NOT NULL UNIQUE,
    kind_id                 INT          NOT NULL,
    city_id                 INT          NOT NULL,
    address_line            VARCHAR(200) NOT NULL,
    /* Filled by an ALTER at the foot of this file -- "User" does not exist
       yet, and "User" points back here for its home location. */
    in_charge_user_id       INT          NULL,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default              BOOLEAN      NOT NULL DEFAULT FALSE,
    /* Claim / damaged stock must never be counted as sellable. */
    exclude_from_sellable   BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_location_kind FOREIGN KEY (kind_id)
        REFERENCES "LocationKind" (kind_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_location_city FOREIGN KEY (city_id)
        REFERENCES "City" (city_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Document numbering: ORD-26-0142, INV-26-8867, GRN-26-0089 ... */
CREATE TABLE "DocumentSeries" (
    series_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_key       VARCHAR(30)  NOT NULL UNIQUE,
    label            VARCHAR(60)  NOT NULL,
    prefix           VARCHAR(10)  NOT NULL UNIQUE,
    include_year     BOOLEAN      NOT NULL DEFAULT TRUE,
    padding          SMALLINT     NOT NULL DEFAULT 4 CHECK (padding BETWEEN 1 AND 10),
    next_number      INT          NOT NULL DEFAULT 1 CHECK (next_number > 0)
);

/* The financial calendar. Year End closes a period; a closed period must
   refuse new postings, which the backend checks against is_closed. */
CREATE TABLE "FiscalPeriod" (
    period_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_name        VARCHAR(20)  NOT NULL UNIQUE,
    period_year        SMALLINT     NOT NULL,
    period_month       SMALLINT     NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    start_date         DATE         NOT NULL,
    end_date           DATE         NOT NULL,
    is_closed          BOOLEAN      NOT NULL DEFAULT FALSE,
    closed_by_user_id  INT          NULL,
    closed_at          DATE         NULL,
    CONSTRAINT uq_period_year_month UNIQUE (period_year, period_month),
    CONSTRAINT ck_period_dates CHECK (end_date >= start_date),
    /* Closed means somebody closed it -- the two fields move together. */
    CONSTRAINT ck_period_closed_by CHECK (
        (is_closed = FALSE AND closed_by_user_id IS NULL AND closed_at IS NULL)
        OR (is_closed = TRUE AND closed_by_user_id IS NOT NULL AND closed_at IS NOT NULL)
    )
);


/* ===========================================================================
   SECTION 3 -- PEOPLE
   Role (parent)  ->  User (child)  ->  Employee / Party (subtypes)
   Exactly the shape asked for: role(roleid) then user(userid, roleid, ...).
   Staff, customers and suppliers are all users; what differs is the role and
   which subtype row hangs off the user.
   =========================================================================== */

CREATE TABLE "User" (
    user_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id             INT          NOT NULL,
    /* Copied from "Role" only so the CHECK below can see it. The composite FK
       to "Role" (role_id, requires_email) with ON UPDATE CASCADE means it can
       never drift from the parent -- change the role's rule and every user
       row follows automatically. This is the trigger-free way to say
       "staff must have an e-mail, customers and suppliers need not". */
    requires_email      BOOLEAN      NOT NULL,
    full_name           VARCHAR(120) NOT NULL,
    email               VARCHAR(120) NULL UNIQUE,
    phone               VARCHAR(30)  NULL,
    password_hash       VARCHAR(200) NULL,
    primary_location_id INT          NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          DATE         NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT fk_user_role FOREIGN KEY (role_id)
        REFERENCES "Role" (role_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_user_email_rule FOREIGN KEY (role_id, requires_email)
        REFERENCES "Role" (role_id, requires_email)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_user_location FOREIGN KEY (primary_location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE SET NULL,

    /* THE RULE. Super Admin / Accountant / Order Dept / Sales cannot be saved
       without an e-mail; Customer / Supplier / Customer & Supplier can. The
       column UNIQUE above still stops two people sharing one address, and
       PostgreSQL allows any number of NULLs in a UNIQUE column, so every
       party may be left blank. */
    CONSTRAINT ck_user_email_required CHECK (
        requires_email = FALSE OR email IS NOT NULL
    ),
    CONSTRAINT ck_user_email_shape CHECK (
        email IS NULL OR email LIKE '%_@_%.__%'
    ),
    /* Anyone who signs in needs a password; parties never sign in. */
    CONSTRAINT ck_user_password CHECK (
        requires_email = FALSE OR password_hash IS NOT NULL
    )
);

ALTER TABLE "Location"
    ADD CONSTRAINT fk_location_incharge FOREIGN KEY (in_charge_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "FiscalPeriod"
    ADD CONSTRAINT fk_period_closed_by FOREIGN KEY (closed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL;

/* Staff subtype. user_id is both PK and FK -- one employee row per user, and
   it disappears with the user. */
CREATE TABLE "Employee" (
    user_id          INT          PRIMARY KEY,
    employee_code    VARCHAR(15)  NOT NULL UNIQUE,
    is_locked        BOOLEAN      NOT NULL DEFAULT FALSE,
    joined_on        DATE         NOT NULL DEFAULT CURRENT_DATE,
    last_login_at    TIMESTAMP    NULL,
    CONSTRAINT fk_employee_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Customer / supplier subtype. Whether a party buys, supplies or both is
   already carried by its role, so it is not repeated here. */
CREATE TABLE "Party" (
    user_id                INT          PRIMARY KEY,
    party_code             VARCHAR(15)  NOT NULL UNIQUE,
    legal_name             VARCHAR(200) NOT NULL,
    display_name           VARCHAR(150) NULL,
    category_id            INT          NOT NULL,
    city_id                INT          NOT NULL,
    address_line           VARCHAR(200) NULL,
    alt_phone              VARCHAR(30)  NULL,
    industry               VARCHAR(100) NULL,
    /* One tax registration cannot belong to two businesses. Nullable: most
       small shops are not registered at all. */
    ntn                    VARCHAR(20)  NULL UNIQUE,
    strn                   VARCHAR(30)  NULL UNIQUE,
    cnic                   VARCHAR(20)  NULL UNIQUE,
    credit_limit           DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (credit_limit >= 0),
    credit_days            INT          NOT NULL DEFAULT 0 CHECK (credit_days >= 0),
    hold_policy_id         INT          NOT NULL,
    opening_balance        DECIMAL(14,2) NOT NULL DEFAULT 0,
    /* The rep who owns the relationship. Must be a member of staff. */
    sales_person_user_id   INT          NULL,
    default_location_id    INT          NULL,
    rating                 CHAR(1)      NOT NULL DEFAULT 'B'
        CHECK (rating IN ('A','B','C','D')),
    notes                  VARCHAR(500) NULL,

    CONSTRAINT fk_party_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_party_category FOREIGN KEY (category_id)
        REFERENCES "PartyCategory" (category_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_party_city FOREIGN KEY (city_id)
        REFERENCES "City" (city_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_party_hold_policy FOREIGN KEY (hold_policy_id)
        REFERENCES "CreditHoldPolicy" (policy_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_party_salesperson FOREIGN KEY (sales_person_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_party_location FOREIGN KEY (default_location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* A role holds many permissions; a permission belongs to many roles. */
CREATE TABLE "RolePermission" (
    role_id          INT NOT NULL,
    permission_id    INT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id)
        REFERENCES "Role" (role_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id)
        REFERENCES "Permission" (permission_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* A user may work out of several locations (the Users screen ticks a list). */
CREATE TABLE "UserLocation" (
    user_id          INT NOT NULL,
    location_id      INT NOT NULL,
    PRIMARY KEY (user_id, location_id),
    CONSTRAINT fk_ul_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ul_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Notification switches from Profile -> Preferences. */
CREATE TABLE "UserPreference" (
    user_id          INT          NOT NULL,
    pref_key         VARCHAR(40)  NOT NULL,
    pref_value       VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, pref_key),
    CONSTRAINT fk_pref_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 4 -- COURIERS AND DELIVERY CHANNELS
   =========================================================================== */

/* Every carrier the goods can leave on: courier companies, cargo companies,
   freight operators and the in-house rider. */
CREATE TABLE "Courier" (
    courier_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_name           VARCHAR(80)  NOT NULL UNIQUE,
    short_name             VARCHAR(30)  NOT NULL,
    contact_person         VARCHAR(80)  NULL,
    phone                  VARCHAR(30)  NULL,
    /* Days the courier holds cash-on-delivery money before settling. */
    cod_settlement_days    SMALLINT     NOT NULL DEFAULT 0 CHECK (cod_settlement_days >= 0),
    booking_charge         DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (booking_charge >= 0),
    cod_fee_percent        DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (cod_fee_percent BETWEEN 0 AND 100),
    tracking_url_template  VARCHAR(200) NULL,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE
);

/* How goods leave: own team, online courier, local cargo, heavy freight.
   Each route has a different person who can say "it arrived", which is the
   whole problem this system was built to solve. */
CREATE TABLE "DeliveryChannel" (
    channel_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_key            VARCHAR(20)  NOT NULL UNIQUE,
    channel_name           VARCHAR(60)  NOT NULL,
    description            VARCHAR(200) NOT NULL,
    /* Which role is chased for the confirmation. */
    confirmed_by_role_id   INT          NOT NULL,
    remind_after_days      SMALLINT     NOT NULL DEFAULT 0 CHECK (remind_after_days >= 0),
    remind_every_hours     SMALLINT     NOT NULL DEFAULT 24 CHECK (remind_every_hours > 0),
    auto_confirm           BOOLEAN      NOT NULL DEFAULT FALSE,
    /* Freight and cargo have no tracking feed -- the bilty receipt is the
       only proof, so its number is mandatory on those channels. */
    requires_bilty         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_channel_role FOREIGN KEY (confirmed_by_role_id)
        REFERENCES "Role" (role_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* The frontend keeps a carriers[] array on each channel. An array is not
   1NF, so it becomes this junction. */
CREATE TABLE "ChannelCarrier" (
    channel_id       INT NOT NULL,
    courier_id       INT NOT NULL,
    PRIMARY KEY (channel_id, courier_id),
    CONSTRAINT fk_cc_channel FOREIGN KEY (channel_id)
        REFERENCES "DeliveryChannel" (channel_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_cc_courier FOREIGN KEY (courier_id)
        REFERENCES "Courier" (courier_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 5 -- CATALOGUE AND STOCK ON HAND
   =========================================================================== */

/* Self-referencing tree: Accessories -> Earbuds, Power -> Chargers ... */
CREATE TABLE "Category" (
    category_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name       VARCHAR(80)  NOT NULL UNIQUE,
    parent_category_id  INT          NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id)
        REFERENCES "Category" (category_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* "Brand" in this catalogue answers "which handset does this fit?" -- the
   goods are all own-brand. Kept under the name the staff already use. */
CREATE TABLE "Brand" (
    brand_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_code       CHAR(2)      NOT NULL UNIQUE,
    brand_name       VARCHAR(60)  NOT NULL UNIQUE,
    description      VARCHAR(150) NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE "Product" (
    product_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku              VARCHAR(30)  NOT NULL UNIQUE,
    product_name     VARCHAR(150) NOT NULL,
    description      VARCHAR(300) NULL,
    category_id      INT          NOT NULL,
    brand_id         INT          NOT NULL,
    /* Pieces in one packet / carton. */
    packing          INT          NOT NULL DEFAULT 1 CHECK (packing > 0),
    min_qty          INT          NOT NULL DEFAULT 0 CHECK (min_qty >= 0),
    max_qty          INT          NOT NULL DEFAULT 0 CHECK (max_qty >= 0),
    opening_cost     DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (opening_cost >= 0),
    cost_price       DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
    sale_price       DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (sale_price >= 0),
    tax_rate_percent DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (tax_rate_percent BETWEEN 0 AND 100),
    hide_stock       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    image_url        VARCHAR(300) NULL,
    created_at       DATE         NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_product_max_qty CHECK (max_qty = 0 OR max_qty >= min_qty),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES "Category" (category_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id)
        REFERENCES "Brand" (brand_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Policy allows several barcodes per item, so they cannot live in a column. */
CREATE TABLE "ProductBarcode" (
    barcode_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       INT          NOT NULL,
    barcode          VARCHAR(40)  NOT NULL UNIQUE,
    CONSTRAINT fk_barcode_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Stock in hand, per item per location. Quantity is deliberately allowed to
   go negative: the live catalogue carries known discrepancies (-1, -975)
   that must be visible until somebody counts the shelf. */
CREATE TABLE "StockBalance" (
    product_id       INT NOT NULL,
    location_id      INT NOT NULL,
    quantity         INT NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id, location_id),
    CONSTRAINT fk_sb_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sb_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 6 -- ACCOUNTING CORE
   ---------------------------------------------------------------------------
   ONE SOURCE OF TRUTH. Every rupee that ever moves lands in exactly one
   place: "JournalEntryLine". Nothing else stores a balance.

       Ledger        = the lines of one account, ordered by date
       Trial balance = SUM(debit), SUM(credit) grouped by account
       Manual entry  = a "JournalEntry" whose type is JOURNAL, keyed by hand
       P&L / Balance sheet = the same sums rolled up by account type -> group

   "Account" therefore carries an opening_balance and nothing else. A stored
   running balance would be a second truth that drifts the first time
   somebody edits an entry.
   =========================================================================== */

CREATE TABLE "AccountGroup" (
    group_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name        VARCHAR(40)  NOT NULL UNIQUE,
    /* TRUE  -> shows on the Balance Sheet
       FALSE -> shows on the Income Statement */
    on_balance_sheet  BOOLEAN      NOT NULL
);

/* The taxonomy the business already uses: ACR for receivables, E for
   expenses, R for revenue, and so on. */
CREATE TABLE "AccountType" (
    account_type_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name         VARCHAR(60)  NOT NULL UNIQUE,
    group_id          INT          NOT NULL,
    code_prefix       VARCHAR(6)   NOT NULL UNIQUE,
    code_length       SMALLINT     NOT NULL DEFAULT 7 CHECK (code_length BETWEEN 1 AND 12),
    /* TRUE = debit-normal (assets, expenses). FALSE = credit-normal. A
       two-row lookup would earn nothing here. */
    is_debit_normal   BOOLEAN      NOT NULL,
    /* Built-ins the posting logic depends on: renameable, not deletable. */
    is_system         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_acctype_group FOREIGN KEY (group_id)
        REFERENCES "AccountGroup" (group_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "Account" (
    account_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code       VARCHAR(15)  NOT NULL UNIQUE,
    account_name       VARCHAR(100) NOT NULL,
    parent_account_id  INT          NULL,
    account_type_id    INT          NOT NULL,
    /* A group heading carries no postings of its own. */
    is_group           BOOLEAN      NOT NULL DEFAULT FALSE,
    opening_balance    DECIMAL(14,2) NOT NULL DEFAULT 0,
    currency_code      CHAR(3)      NOT NULL DEFAULT 'PKR',
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_account_parent FOREIGN KEY (parent_account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_account_type FOREIGN KEY (account_type_id)
        REFERENCES "AccountType" (account_type_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "JournalEntry" (
    entry_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_no            VARCHAR(20)  NOT NULL UNIQUE,
    entry_date          DATE         NOT NULL,
    entry_type_id       INT          NOT NULL,
    period_id           INT          NOT NULL,
    location_id         INT          NOT NULL,
    /* The document that caused it: INV-26-0142, GRN-26-0089, VCH-26-0089.
       NULL on a hand-keyed manual entry. */
    reference_no        VARCHAR(30)  NULL,
    narration           VARCHAR(500) NOT NULL,
    status_id           INT          NOT NULL,
    created_by_user_id  INT          NOT NULL,
    posted_by_user_id   INT          NULL,
    created_at          DATE         NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT fk_je_type FOREIGN KEY (entry_type_id)
        REFERENCES "JournalEntryType" (entry_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_je_period FOREIGN KEY (period_id)
        REFERENCES "FiscalPeriod" (period_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_je_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_je_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_je_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_je_posted_by FOREIGN KEY (posted_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* The single source of truth. Every ledger, statement and report reads here. */
CREATE TABLE "JournalEntryLine" (
    line_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id         INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    account_id       INT          NOT NULL,
    /* Set on receivable / payable lines so a customer or supplier statement
       is one WHERE clause away. NULL on every other line. */
    party_user_id    INT          NULL,
    description      VARCHAR(300) NULL,
    debit_amount     DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (debit_amount >= 0),
    credit_amount    DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (credit_amount >= 0),
    CONSTRAINT uq_jel_line UNIQUE (entry_id, line_no),
    /* A line is a debit or a credit, never both and never neither. */
    CONSTRAINT ck_jel_one_side CHECK (
        (debit_amount = 0 OR credit_amount = 0)
        AND (debit_amount + credit_amount) > 0
    ),
    CONSTRAINT fk_jel_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_jel_account FOREIGN KEY (account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_jel_party FOREIGN KEY (party_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* Money in and money out. A posted voucher owns one journal entry, so the
   cash book and the ledger can never disagree. */
CREATE TABLE "Voucher" (
    voucher_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no           VARCHAR(20)  NOT NULL UNIQUE,
    voucher_type_id      INT          NOT NULL,
    voucher_date         DATE         NOT NULL,
    location_id          INT          NOT NULL,
    /* NULL on a journal voucher, which faces no party. */
    party_user_id        INT          NULL,
    /* Which drawer or bank account the money touched. NULL only on a journal
       voucher, which moves nothing between a drawer and a party. */
    cash_bank_account_id INT          NULL,
    amount               DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    method_id            INT          NOT NULL,
    payment_provider     VARCHAR(60)  NULL,
    reference_no         VARCHAR(50)  NULL,
    wallet_txn_id        VARCHAR(50)  NULL,
    narration            VARCHAR(300) NOT NULL,
    status_id            INT          NOT NULL,
    entry_id             INT          NULL,
    created_by_user_id   INT          NOT NULL,
    CONSTRAINT fk_voucher_type FOREIGN KEY (voucher_type_id)
        REFERENCES "VoucherType" (voucher_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_voucher_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_voucher_party FOREIGN KEY (party_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_voucher_account FOREIGN KEY (cash_bank_account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_voucher_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_voucher_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_voucher_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_voucher_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* One receipt spread over three invoices -- the reason invoices do not carry
   a stored "paid" column. What an invoice has been paid is the sum of its
   allocations, and nothing else. */
CREATE TABLE "VoucherAllocation" (
    allocation_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id           INT          NOT NULL,
    sales_invoice_id     INT          NULL,
    purchase_invoice_id  INT          NULL,
    amount               DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    /* A receipt settles a sale invoice; a payment settles a purchase
       invoice. Exactly one, never both. */
    CONSTRAINT ck_alloc_one_target CHECK (
        (sales_invoice_id IS NOT NULL AND purchase_invoice_id IS NULL)
        OR (sales_invoice_id IS NULL AND purchase_invoice_id IS NOT NULL)
    ),
    CONSTRAINT fk_alloc_voucher FOREIGN KEY (voucher_id)
        REFERENCES "Voucher" (voucher_id) ON UPDATE CASCADE ON DELETE CASCADE
    /* The two invoice FKs are added at the foot of this file -- the invoice
       tables are created further down. */
);

CREATE TABLE "Expense" (
    expense_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_no            VARCHAR(20)  NOT NULL UNIQUE,
    expense_date          DATE         NOT NULL,
    location_id           INT          NOT NULL,
    category_name         VARCHAR(80)  NOT NULL,
    /* Debited: Rent, Utilities, Marketing ... */
    expense_account_id    INT          NOT NULL,
    /* Credited: the cash drawer or bank account it was paid from. */
    paid_from_account_id  INT          NOT NULL,
    amount                DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    vendor_name           VARCHAR(150) NOT NULL,
    method_id             INT          NOT NULL,
    description           VARCHAR(500) NULL,
    status_id             INT          NOT NULL,
    entry_id              INT          NULL,
    created_by_user_id    INT          NOT NULL,
    CONSTRAINT ck_expense_accounts CHECK (expense_account_id <> paid_from_account_id),
    CONSTRAINT fk_expense_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_expense_account FOREIGN KEY (expense_account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_expense_paidfrom FOREIGN KEY (paid_from_account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_expense_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_expense_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_expense_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_expense_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Money a rep took in the field. It does NOT move the customer's ledger --
   it waits for Accounts to confirm the cash actually arrived, and only then
   becomes a voucher. Without that gap a rep could sit on cash for a week and
   the books would still look settled. */
CREATE TABLE "Collection" (
    collection_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no            VARCHAR(20)  NOT NULL UNIQUE,
    customer_user_id      INT          NOT NULL,
    collected_by_user_id  INT          NOT NULL,
    collected_on          DATE         NOT NULL,
    amount                DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    method_id             INT          NOT NULL,
    reference_no          VARCHAR(50)  NULL,
    bank_name             VARCHAR(60)  NULL,
    /* Cheques are routinely post-dated in this trade. */
    cheque_date           DATE         NULL,
    status_id             INT          NOT NULL,
    confirmed_on          DATE         NULL,
    confirmed_by_user_id  INT          NULL,
    /* Filled the moment Accounts confirms it. Until then the ledger is
       untouched. */
    voucher_id            INT          NULL,
    note                  VARCHAR(300) NULL,
    CONSTRAINT ck_collection_confirmed CHECK (
        (confirmed_on IS NULL AND confirmed_by_user_id IS NULL)
        OR (confirmed_on IS NOT NULL AND confirmed_by_user_id IS NOT NULL)
    ),
    CONSTRAINT fk_collection_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_collection_collector FOREIGN KEY (collected_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_collection_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_collection_status FOREIGN KEY (status_id)
        REFERENCES "CollectionStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_collection_confirmer FOREIGN KEY (confirmed_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_collection_voucher FOREIGN KEY (voucher_id)
        REFERENCES "Voucher" (voucher_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* "against: string[]" on the collection screen -- an array, so it becomes a
   child table. An empty set means the money was taken on account. */
CREATE TABLE "CollectionAllocation" (
    allocation_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id    INT          NOT NULL,
    order_id         INT          NOT NULL,
    amount           DECIMAL(14,2) NOT NULL CHECK (amount > 0),
    CONSTRAINT fk_colalloc_collection FOREIGN KEY (collection_id)
        REFERENCES "Collection" (collection_id) ON UPDATE CASCADE ON DELETE CASCADE
    /* order FK added at the foot of the file. */
);

CREATE TABLE "BankReconciliation" (
    reconciliation_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            INT          NOT NULL,
    statement_date        DATE         NOT NULL,
    opening_balance       DECIMAL(14,2) NOT NULL DEFAULT 0,
    closing_balance       DECIMAL(14,2) NOT NULL DEFAULT 0,
    status_id             INT          NOT NULL,
    prepared_by_user_id   INT          NOT NULL,
    finalized_on          DATE         NULL,
    CONSTRAINT uq_recon_account_date UNIQUE (account_id, statement_date),
    CONSTRAINT fk_recon_account FOREIGN KEY (account_id)
        REFERENCES "Account" (account_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_recon_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_recon_preparer FOREIGN KEY (prepared_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* One line off the bank's own statement. matched_line_id points at the
   journal line it was tied to; NULL means still unreconciled. */
CREATE TABLE "BankStatementLine" (
    statement_line_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_id   INT          NOT NULL,
    line_date           DATE         NOT NULL,
    description         VARCHAR(200) NOT NULL,
    /* Signed: positive is money in, negative is money out. */
    amount              DECIMAL(14,2) NOT NULL CHECK (amount <> 0),
    matched_line_id     INT          NULL,
    CONSTRAINT fk_bsl_recon FOREIGN KEY (reconciliation_id)
        REFERENCES "BankReconciliation" (reconciliation_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_bsl_matched FOREIGN KEY (matched_line_id)
        REFERENCES "JournalEntryLine" (line_id) ON UPDATE CASCADE ON DELETE SET NULL
);


/* ===========================================================================
   SECTION 7 -- SALES
   Order -> (packing, dispatch) -> Invoice -> Return
   =========================================================================== */

CREATE TABLE "SalesOrder" (
    order_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no              VARCHAR(20)  NOT NULL UNIQUE,
    customer_user_id      INT          NOT NULL,
    location_id           INT          NOT NULL,
    sales_person_user_id  INT          NULL,
    order_date            DATE         NOT NULL,
    delivery_date         DATE         NULL,
    status_id             INT          NOT NULL,
    method_id             INT          NOT NULL,
    subtotal              DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount       DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount            DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount          DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    /* Why the owner had to look at it: "already PKR 84,500 out; this pushes
       the balance PKR 30,500 over limit". */
    credit_hold_reason    VARCHAR(300) NULL,
    notes                 VARCHAR(500) NULL,
    created_by_user_id    INT          NOT NULL,
    created_at            DATE         NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_order_dates CHECK (delivery_date IS NULL OR delivery_date >= order_date),
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_salesperson FOREIGN KEY (sales_person_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_order_status FOREIGN KEY (status_id)
        REFERENCES "OrderStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "CollectionAllocation"
    ADD CONSTRAINT fk_colalloc_order FOREIGN KEY (order_id)
        REFERENCES "SalesOrder" (order_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE "SalesOrderItem" (
    order_item_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          INT          NOT NULL,
    line_no           SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id        INT          NOT NULL,
    quantity          INT          NOT NULL CHECK (quantity > 0),
    unit_price        DECIMAL(14,2) NOT NULL CHECK (unit_price >= 0),
    discount_percent  DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (discount_percent BETWEEN 0 AND 100),
    tax_percent       DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (tax_percent BETWEEN 0 AND 100),
    line_total        DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (line_total >= 0),
    CONSTRAINT uq_soi_line UNIQUE (order_id, line_no),
    /* The same item twice on one order is a keying mistake, not a discount. */
    CONSTRAINT uq_soi_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_soi_order FOREIGN KEY (order_id)
        REFERENCES "SalesOrder" (order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_soi_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* order_id is NULL for a counter sale -- somebody walks in, buys and leaves
   without an order ever existing. */
CREATE TABLE "SalesInvoice" (
    invoice_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no          VARCHAR(20)  NOT NULL UNIQUE,
    order_id            INT          NULL UNIQUE,
    customer_user_id    INT          NOT NULL,
    location_id         INT          NOT NULL,
    invoice_date        DATE         NOT NULL,
    due_date            DATE         NOT NULL,
    subtotal            DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount     DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount          DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount        DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    status_id           INT          NOT NULL,
    method_id           INT          NOT NULL,
    entry_id            INT          NULL,
    created_by_user_id  INT          NOT NULL,
    CONSTRAINT ck_invoice_due CHECK (due_date >= invoice_date),
    CONSTRAINT fk_si_order FOREIGN KEY (order_id)
        REFERENCES "SalesOrder" (order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_status FOREIGN KEY (status_id)
        REFERENCES "InvoiceStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_si_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_si_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "VoucherAllocation"
    ADD CONSTRAINT fk_alloc_sales_invoice FOREIGN KEY (sales_invoice_id)
        REFERENCES "SalesInvoice" (invoice_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE "SalesInvoiceItem" (
    invoice_item_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id        INT          NOT NULL,
    line_no           SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id        INT          NOT NULL,
    quantity          INT          NOT NULL CHECK (quantity > 0),
    unit_price        DECIMAL(14,2) NOT NULL CHECK (unit_price >= 0),
    discount_percent  DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (discount_percent BETWEEN 0 AND 100),
    tax_percent       DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (tax_percent BETWEEN 0 AND 100),
    /* Cost at the moment of sale -- what the profit report subtracts. Stored
       because today's cost price is not the cost this piece was bought at. */
    unit_cost         DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    line_total        DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (line_total >= 0),
    CONSTRAINT uq_sii_line UNIQUE (invoice_id, line_no),
    CONSTRAINT uq_sii_product UNIQUE (invoice_id, product_id),
    CONSTRAINT fk_sii_invoice FOREIGN KEY (invoice_id)
        REFERENCES "SalesInvoice" (invoice_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sii_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "SalesReturn" (
    return_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no           VARCHAR(20)  NOT NULL UNIQUE,
    invoice_id          INT          NOT NULL,
    customer_user_id    INT          NOT NULL,
    location_id         INT          NOT NULL,
    return_date         DATE         NOT NULL,
    reason              VARCHAR(300) NOT NULL,
    refund_method_id    INT          NOT NULL,
    status_id           INT          NOT NULL,
    entry_id            INT          NULL,
    created_by_user_id  INT          NOT NULL,
    CONSTRAINT fk_sr_invoice FOREIGN KEY (invoice_id)
        REFERENCES "SalesInvoice" (invoice_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sr_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sr_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sr_method FOREIGN KEY (refund_method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sr_status FOREIGN KEY (status_id)
        REFERENCES "ReturnStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sr_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_sr_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "SalesReturnItem" (
    return_item_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id            INT          NOT NULL,
    line_no              SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id           INT          NOT NULL,
    quantity             INT          NOT NULL CHECK (quantity > 0),
    unit_price           DECIMAL(14,2) NOT NULL CHECK (unit_price >= 0),
    condition_id         INT          NOT NULL,
    /* Where a resalable piece goes back on the shelf. Damaged pieces have
       no restock location -- they go to claim stock instead. */
    restock_location_id  INT          NULL,
    CONSTRAINT uq_sri_line UNIQUE (return_id, line_no),
    CONSTRAINT fk_sri_return FOREIGN KEY (return_id)
        REFERENCES "SalesReturn" (return_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sri_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sri_condition FOREIGN KEY (condition_id)
        REFERENCES "ReturnCondition" (condition_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sri_location FOREIGN KEY (restock_location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE SET NULL
);


/* ===========================================================================
   SECTION 8 -- PURCHASES
   Order to supplier -> Stock received (GRN) -> Purchase invoice -> Return
   =========================================================================== */

CREATE TABLE "PurchaseOrder" (
    po_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no                VARCHAR(20)  NOT NULL UNIQUE,
    supplier_user_id     INT          NOT NULL,
    location_id          INT          NOT NULL,
    po_date              DATE         NOT NULL,
    expected_date        DATE         NULL,
    status_id            INT          NOT NULL,
    subtotal             DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    /* Trade discount the supplier gave off the line rates. */
    discount_amount      DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount           DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total_amount         DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    notes                VARCHAR(500) NULL,
    created_by_user_id   INT          NOT NULL,
    approved_by_user_id  INT          NULL,
    CONSTRAINT ck_po_dates CHECK (expected_date IS NULL OR expected_date >= po_date),
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_po_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_po_status FOREIGN KEY (status_id)
        REFERENCES "PurchaseOrderStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_po_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_po_approved_by FOREIGN KEY (approved_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "PurchaseOrderItem" (
    po_item_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id            INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id       INT          NOT NULL,
    quantity         INT          NOT NULL CHECK (quantity > 0),
    unit_cost        DECIMAL(14,2) NOT NULL CHECK (unit_cost >= 0),
    tax_percent      DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (tax_percent BETWEEN 0 AND 100),
    line_total       DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (line_total >= 0),
    CONSTRAINT uq_poi_line UNIQUE (po_id, line_no),
    CONSTRAINT uq_poi_product UNIQUE (po_id, product_id),
    CONSTRAINT fk_poi_po FOREIGN KEY (po_id)
        REFERENCES "PurchaseOrder" (po_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_poi_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* Stock received. po_id is nullable: goods sometimes arrive against a phone
   call with the paperwork following later. */
CREATE TABLE "GoodsReceipt" (
    grn_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_no                VARCHAR(20)  NOT NULL UNIQUE,
    po_id                 INT          NULL,
    supplier_user_id      INT          NOT NULL,
    location_id           INT          NOT NULL,
    receipt_date          DATE         NOT NULL,
    delivery_note_no      VARCHAR(50)  NOT NULL,
    vehicle_no            VARCHAR(30)  NULL,
    total_value           DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_value >= 0),
    status_id             INT          NOT NULL,
    entry_id              INT          NULL,
    received_by_user_id   INT          NOT NULL,
    notes                 VARCHAR(500) NULL,
    CONSTRAINT fk_grn_po FOREIGN KEY (po_id)
        REFERENCES "PurchaseOrder" (po_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_grn_supplier FOREIGN KEY (supplier_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_grn_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_grn_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_grn_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_grn_receiver FOREIGN KEY (received_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "GoodsReceiptItem" (
    grn_item_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grn_id           INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id       INT          NOT NULL,
    qty_received     INT          NOT NULL CHECK (qty_received >= 0),
    /* Broken on arrival. Never lands on the sellable shelf. */
    qty_damaged      INT          NOT NULL DEFAULT 0 CHECK (qty_damaged >= 0),
    unit_cost        DECIMAL(14,2) NOT NULL CHECK (unit_cost >= 0),
    batch_no         VARCHAR(50)  NULL,
    expiry_date      DATE         NULL,
    CONSTRAINT ck_grni_damaged CHECK (qty_damaged <= qty_received),
    CONSTRAINT uq_grni_line UNIQUE (grn_id, line_no),
    CONSTRAINT uq_grni_product UNIQUE (grn_id, product_id),
    CONSTRAINT fk_grni_grn FOREIGN KEY (grn_id)
        REFERENCES "GoodsReceipt" (grn_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_grni_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "PurchaseInvoice" (
    pi_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no           VARCHAR(20)  NOT NULL UNIQUE,
    /* The supplier's own number. Two invoices from one supplier cannot share
       it; two different suppliers may well both use "INV-001". */
    supplier_invoice_no  VARCHAR(50)  NOT NULL,
    supplier_user_id     INT          NOT NULL,
    po_id                INT          NULL,
    invoice_date         DATE         NOT NULL,
    due_date             DATE         NOT NULL,
    subtotal             DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    discount_amount      DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    tax_amount           DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    /* Withholding tax deducted at source. */
    wht_amount           DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (wht_amount >= 0),
    total_amount         DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    status_id            INT          NOT NULL,
    method_id            INT          NOT NULL,
    entry_id             INT          NULL,
    created_by_user_id   INT          NOT NULL,
    CONSTRAINT uq_pi_supplier_ref UNIQUE (supplier_user_id, supplier_invoice_no),
    CONSTRAINT ck_pi_due CHECK (due_date >= invoice_date),
    CONSTRAINT fk_pi_supplier FOREIGN KEY (supplier_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pi_po FOREIGN KEY (po_id)
        REFERENCES "PurchaseOrder" (po_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_pi_status FOREIGN KEY (status_id)
        REFERENCES "InvoiceStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pi_method FOREIGN KEY (method_id)
        REFERENCES "PaymentMethod" (method_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pi_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_pi_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "VoucherAllocation"
    ADD CONSTRAINT fk_alloc_purchase_invoice FOREIGN KEY (purchase_invoice_id)
        REFERENCES "PurchaseInvoice" (pi_id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE "PurchaseInvoiceItem" (
    pi_item_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pi_id            INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id       INT          NOT NULL,
    quantity         INT          NOT NULL CHECK (quantity > 0),
    unit_cost        DECIMAL(14,2) NOT NULL CHECK (unit_cost >= 0),
    tax_percent      DECIMAL(5,2)  NOT NULL DEFAULT 0
        CHECK (tax_percent BETWEEN 0 AND 100),
    line_total       DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (line_total >= 0),
    CONSTRAINT uq_pii_line UNIQUE (pi_id, line_no),
    CONSTRAINT uq_pii_product UNIQUE (pi_id, product_id),
    CONSTRAINT fk_pii_pi FOREIGN KEY (pi_id)
        REFERENCES "PurchaseInvoice" (pi_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pii_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "PurchaseReturn" (
    pr_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no            VARCHAR(20)  NOT NULL UNIQUE,
    pi_id                INT          NOT NULL,
    supplier_user_id     INT          NOT NULL,
    location_id          INT          NOT NULL,
    return_date          DATE         NOT NULL,
    reason               VARCHAR(300) NOT NULL,
    status_id            INT          NOT NULL,
    entry_id             INT          NULL,
    created_by_user_id   INT          NOT NULL,
    CONSTRAINT fk_pr_pi FOREIGN KEY (pi_id)
        REFERENCES "PurchaseInvoice" (pi_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pr_supplier FOREIGN KEY (supplier_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pr_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pr_status FOREIGN KEY (status_id)
        REFERENCES "ReturnStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pr_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_pr_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "PurchaseReturnItem" (
    pr_item_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pr_id            INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id       INT          NOT NULL,
    quantity         INT          NOT NULL CHECK (quantity > 0),
    unit_cost        DECIMAL(14,2) NOT NULL CHECK (unit_cost >= 0),
    CONSTRAINT uq_pri_line UNIQUE (pr_id, line_no),
    CONSTRAINT fk_pri_pr FOREIGN KEY (pr_id)
        REFERENCES "PurchaseReturn" (pr_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pri_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 9 -- STOCK MOVEMENT
   =========================================================================== */

CREATE TABLE "StockTransfer" (
    transfer_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no          VARCHAR(20)  NOT NULL UNIQUE,
    from_location_id     INT          NOT NULL,
    to_location_id       INT          NOT NULL,
    transfer_date        DATE         NOT NULL,
    status_id            INT          NOT NULL,
    initiated_by_user_id INT          NOT NULL,
    approved_by_user_id  INT          NULL,
    received_on          DATE         NULL,
    notes                VARCHAR(500) NULL,
    /* Moving stock to the shelf it is already on is always a mistake. */
    CONSTRAINT ck_transfer_locations CHECK (from_location_id <> to_location_id),
    CONSTRAINT fk_trf_from FOREIGN KEY (from_location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_trf_to FOREIGN KEY (to_location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_trf_status FOREIGN KEY (status_id)
        REFERENCES "TransferStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_trf_initiator FOREIGN KEY (initiated_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_trf_approver FOREIGN KEY (approved_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "StockTransferItem" (
    transfer_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id      INT          NOT NULL,
    line_no          SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id       INT          NOT NULL,
    quantity         INT          NOT NULL CHECK (quantity > 0),
    CONSTRAINT uq_sti_line UNIQUE (transfer_id, line_no),
    CONSTRAINT uq_sti_product UNIQUE (transfer_id, product_id),
    CONSTRAINT fk_sti_transfer FOREIGN KEY (transfer_id)
        REFERENCES "StockTransfer" (transfer_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sti_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "StockAdjustment" (
    adjustment_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_no       VARCHAR(20)  NOT NULL UNIQUE,
    location_id         INT          NOT NULL,
    adjustment_date     DATE         NOT NULL,
    reason_id           INT          NOT NULL,
    reason_notes        VARCHAR(500) NOT NULL,
    status_id           INT          NOT NULL,
    entry_id            INT          NULL,
    created_by_user_id  INT          NOT NULL,
    CONSTRAINT fk_adj_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_adj_reason FOREIGN KEY (reason_id)
        REFERENCES "AdjustmentReason" (reason_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_adj_status FOREIGN KEY (status_id)
        REFERENCES "PostingStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_adj_entry FOREIGN KEY (entry_id)
        REFERENCES "JournalEntry" (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_adj_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "StockAdjustmentItem" (
    adjustment_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id      INT          NOT NULL,
    line_no            SMALLINT     NOT NULL CHECK (line_no > 0),
    product_id         INT          NOT NULL,
    /* Both sides are kept so the correction can be read back years later
       without replaying every movement. */
    current_qty        INT          NOT NULL,
    new_qty            INT          NOT NULL,
    CONSTRAINT ck_adji_changed CHECK (new_qty <> current_qty),
    CONSTRAINT uq_adji_line UNIQUE (adjustment_id, line_no),
    CONSTRAINT uq_adji_product UNIQUE (adjustment_id, product_id),
    CONSTRAINT fk_adji_adjustment FOREIGN KEY (adjustment_id)
        REFERENCES "StockAdjustment" (adjustment_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_adji_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* HISTORY ENTITY -- the stock ledger behind the Stock History screen. Every
   piece that enters or leaves any shelf writes one row here, whatever caused
   it. "StockBalance" is the running figure; this is how it got there. */
CREATE TABLE "StockMovement" (
    movement_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        INT          NOT NULL,
    location_id       INT          NOT NULL,
    movement_type_id  INT          NOT NULL,
    moved_at          TIMESTAMP    NOT NULL,
    /* The document that caused it: ORD-26-0142, GRN-26-0089, TRF-26-0012. */
    reference_no      VARCHAR(30)  NOT NULL,
    /* Signed. Negative takes stock off the shelf. */
    quantity          INT          NOT NULL CHECK (quantity <> 0),
    balance_after     INT          NOT NULL,
    user_id           INT          NOT NULL,
    CONSTRAINT fk_sm_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sm_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sm_type FOREIGN KEY (movement_type_id)
        REFERENCES "MovementType" (movement_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_sm_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 10 -- DELIVERY, CLAIMS AND FIELD WORK
   =========================================================================== */

/* One consignment. Everything about how the goods left and whether they
   arrived lives here, so "SalesOrder" never repeats a carrier or a tracking
   number. No delivery row means the order has not been dispatched. */
CREATE TABLE "Delivery" (
    delivery_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_no            VARCHAR(20)  NOT NULL UNIQUE,
    order_id               INT          NOT NULL,
    invoice_id             INT          NULL,
    channel_id             INT          NOT NULL,
    courier_id             INT          NULL,
    /* Courier tracking number, or the bilty number for freight. Required on
       any channel whose requires_bilty flag is set -- the backend checks it
       against "DeliveryChannel" at dispatch time. */
    tracking_no            VARCHAR(40)  NULL,
    booked_date            DATE         NOT NULL,
    expected_date          DATE         NULL,
    delivered_date         DATE         NULL,
    status_id              INT          NOT NULL,
    parcels                INT          NOT NULL DEFAULT 1 CHECK (parcels > 0),
    weight_kg              DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (weight_kg >= 0),
    /* What the courier must collect from the customer. 0 = already paid. */
    cod_amount             DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (cod_amount >= 0),
    is_cod_settled         BOOLEAN      NOT NULL DEFAULT FALSE,
    booking_charge         DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (booking_charge >= 0),
    /* How many times somebody was asked and did not answer. */
    reminders_sent         SMALLINT     NOT NULL DEFAULT 0 CHECK (reminders_sent >= 0),
    confirmed_by_user_id   INT          NULL,
    notes                  VARCHAR(300) NULL,
    CONSTRAINT ck_delivery_dates CHECK (delivered_date IS NULL OR delivered_date >= booked_date),
    /* Cash that never went out cannot have been settled. */
    CONSTRAINT ck_delivery_cod CHECK (cod_amount > 0 OR is_cod_settled = FALSE),
    CONSTRAINT fk_dlv_order FOREIGN KEY (order_id)
        REFERENCES "SalesOrder" (order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dlv_invoice FOREIGN KEY (invoice_id)
        REFERENCES "SalesInvoice" (invoice_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_dlv_channel FOREIGN KEY (channel_id)
        REFERENCES "DeliveryChannel" (channel_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dlv_courier FOREIGN KEY (courier_id)
        REFERENCES "Courier" (courier_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_dlv_status FOREIGN KEY (status_id)
        REFERENCES "DeliveryStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dlv_confirmer FOREIGN KEY (confirmed_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* A shopkeeper brings back one dead battery months later and has no idea
   which invoice it came on. So a claim is recorded against the ITEM, never
   against an order -- original_order_no is free text and always optional. */
CREATE TABLE "Claim" (
    claim_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_no             VARCHAR(20)  NOT NULL UNIQUE,
    customer_user_id     INT          NOT NULL,
    received_on          DATE         NOT NULL,
    received_by_user_id  INT          NOT NULL,
    product_id           INT          NOT NULL,
    quantity             INT          NOT NULL CHECK (quantity > 0),
    /* Cost of the piece, frozen -- this is the write-off figure if the
       supplier refuses. */
    unit_cost            DECIMAL(14,2) NOT NULL CHECK (unit_cost >= 0),
    reason_id            INT          NOT NULL,
    claim_note           VARCHAR(300) NULL,
    original_order_no    VARCHAR(20)  NULL,
    /* What the customer walked away with while the supplier decides. */
    outcome_id           INT          NOT NULL,
    stage_id             INT          NOT NULL,
    supplier_user_id     INT          NULL,
    sent_on              DATE         NULL,
    settled_on           DATE         NULL,
    supplier_note        VARCHAR(300) NULL,
    reminders_sent       SMALLINT     NOT NULL DEFAULT 0 CHECK (reminders_sent >= 0),
    /* Nothing can be settled before it was sent, and nothing is sent before
       it came in. */
    CONSTRAINT ck_claim_sent CHECK (sent_on IS NULL OR sent_on >= received_on),
    CONSTRAINT ck_claim_settled CHECK (
        settled_on IS NULL OR (sent_on IS NOT NULL AND settled_on >= sent_on)
    ),
    /* It cannot be with a supplier without naming the supplier. */
    CONSTRAINT ck_claim_supplier CHECK (
        sent_on IS NULL OR supplier_user_id IS NOT NULL
    ),
    CONSTRAINT fk_claim_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_receiver FOREIGN KEY (received_by_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_product FOREIGN KEY (product_id)
        REFERENCES "Product" (product_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_reason FOREIGN KEY (reason_id)
        REFERENCES "ClaimReason" (reason_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_outcome FOREIGN KEY (outcome_id)
        REFERENCES "ClaimOutcome" (outcome_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_stage FOREIGN KEY (stage_id)
        REFERENCES "ClaimStage" (stage_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_claim_supplier FOREIGN KEY (supplier_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "CustomerVisit" (
    visit_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id      INT          NOT NULL,
    sales_person_user_id  INT          NOT NULL,
    visited_at            TIMESTAMP    NOT NULL,
    outcome_id            INT          NOT NULL,
    notes                 VARCHAR(300) NULL,
    latitude              DECIMAL(9,6) NULL,
    longitude             DECIMAL(9,6) NULL,
    CONSTRAINT fk_visit_customer FOREIGN KEY (customer_user_id)
        REFERENCES "Party" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_visit_rep FOREIGN KEY (sales_person_user_id)
        REFERENCES "Employee" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_visit_outcome FOREIGN KEY (outcome_id)
        REFERENCES "VisitOutcome" (outcome_id) ON UPDATE CASCADE ON DELETE CASCADE
);


/* ===========================================================================
   SECTION 11 -- NOTIFICATIONS AND HISTORY
   Reminders are NOT stored. A claim that has sat too long produces a reminder
   because of its dates; settle it and the reminder disappears on its own.
   Storing them would mean rows to tick off and rows going stale.
   =========================================================================== */

CREATE TABLE "Notification" (
    notification_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INT          NOT NULL,
    severity_id      INT          NOT NULL,
    icon             VARCHAR(40)  NOT NULL,
    title            VARCHAR(120) NOT NULL,
    body             VARCHAR(300) NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    is_read          BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_notif_severity FOREIGN KEY (severity_id)
        REFERENCES "SeverityLevel" (severity_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* HISTORY ENTITY -- Activity History / audit trail. Who did what, to which
   record, from which machine. user_id is nullable because the system itself
   posts entries, and a failed login has no authenticated user. */
CREATE TABLE "ActivityLog" (
    log_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INT          NULL,
    action_name       VARCHAR(30)  NOT NULL,
    entity_type       VARCHAR(40)  NOT NULL,
    entity_reference  VARCHAR(60)  NOT NULL,
    detail            VARCHAR(300) NULL,
    ip_address        VARCHAR(45)  NULL,
    location_id       INT          NULL,
    severity_id       INT          NOT NULL,
    logged_at         TIMESTAMP    NOT NULL,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_log_location FOREIGN KEY (location_id)
        REFERENCES "Location" (location_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_log_severity FOREIGN KEY (severity_id)
        REFERENCES "SeverityLevel" (severity_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* HISTORY ENTITY -- Backup & Restore. */
CREATE TABLE "BackupHistory" (
    backup_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at        TIMESTAMP    NOT NULL,
    backup_type_id    INT          NOT NULL,
    status_id         INT          NOT NULL,
    size_mb           DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (size_mb >= 0),
    destination       VARCHAR(80)  NOT NULL,
    duration_seconds  INT          NOT NULL DEFAULT 0 CHECK (duration_seconds >= 0),
    checksum_hash     VARCHAR(80)  NULL,
    triggered_by_user_id INT       NULL,
    CONSTRAINT fk_backup_type FOREIGN KEY (backup_type_id)
        REFERENCES "BackupType" (backup_type_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_backup_status FOREIGN KEY (status_id)
        REFERENCES "BackupStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_backup_user FOREIGN KEY (triggered_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* ===========================================================================
   END OF SCHEMA -- 84 tables.
   Load 02_seed.sql next, then 03_sequence_reset.sql.
   =========================================================================== */
