/* ===========================================================================
   ADVANCE POS SYSTEM (AdvPOS) -- STATUS HISTORY
   ---------------------------------------------------------------------------
   THIS FILE IS NOT PART OF THE DATABASE.

   01_schema.sql gives every document its CURRENT status and stops there:
   SalesOrder.status_id, Claim.stage_id, Delivery.status_id, and so on. That
   answers "where is this order now?" and nothing else.

   You asked how to also answer "who marked ORD-26-0142 dispatched, and when?"
   -- and asked for it kept separate. Here it is. Load it only if you want the
   trail. Everything else keeps working whether you load it or not.
   ===========================================================================

   THE IDEA
   ---------------------------------------------------------------------------
   A status history table is a plain child of the document. One row per change,
   never updated, never deleted:

       (which document, which status, who did it, when, and why)

   It reuses the SAME status lookup the document already points at, so
   OrderStatusHistory.status_id and SalesOrder.status_id speak one vocabulary.
   No new enums, no triggers -- the backend writes the document and its history
   row inside one transaction, which is two INSERT/UPDATE statements it is
   already issuing anyway.

   WHY KEEP status_id ON THE DOCUMENT AS WELL
   ---------------------------------------------------------------------------
   You could drop SalesOrder.status_id and read the newest history row instead.
   Do not. Every order list, every dashboard count and every reminder filters
   on the current status, and each of those would turn into a "latest row per
   order" subquery. Keeping the column costs one extra write and saves that
   query everywhere.

   So: the column is the current state, the history table is the trail. The
   backend keeps them in step in one transaction:

       BEGIN;
         UPDATE "SalesOrder" SET status_id = 7 WHERE order_id = 1;
         INSERT INTO "OrderStatusHistory"
                (order_id, status_id, changed_by_user_id, changed_at, note)
         VALUES (1, 7, 4, NOW(), 'Handed to the rep on the evening round');
       COMMIT;

   A trigger would do this for you, and would also hide it, break bulk loads,
   and make the seed above impossible to reason about. Two lines in one
   transaction is the simpler answer.
   =========================================================================== */


/* ---------------------------------------------------------------------------
   PATTERN A -- one history table per document  (RECOMMENDED)

   More tables, but every foreign key stays real: an order's history cannot
   accidentally point at an invoice status, and deleting the order takes its
   trail with it.
   --------------------------------------------------------------------------- */

CREATE TABLE "OrderStatusHistory" (
    history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            INT          NOT NULL,
    status_id           INT          NOT NULL,
    changed_by_user_id  INT          NULL,
    changed_at          TIMESTAMP    NOT NULL,
    note                VARCHAR(300) NULL,
    /* The same order cannot be marked the same status twice at the same
       instant -- that is a double-submit, not two events. */
    CONSTRAINT uq_osh_event UNIQUE (order_id, status_id, changed_at),
    CONSTRAINT fk_osh_order FOREIGN KEY (order_id)
        REFERENCES "SalesOrder" (order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_osh_status FOREIGN KEY (status_id)
        REFERENCES "OrderStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    /* SET NULL, not CASCADE: sacking a member of staff must not erase the
       fact that the order was dispatched. */
    CONSTRAINT fk_osh_user FOREIGN KEY (changed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "ClaimStageHistory" (
    history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id            INT          NOT NULL,
    stage_id            INT          NOT NULL,
    changed_by_user_id  INT          NULL,
    changed_at          TIMESTAMP    NOT NULL,
    note                VARCHAR(300) NULL,
    CONSTRAINT uq_csh_event UNIQUE (claim_id, stage_id, changed_at),
    CONSTRAINT fk_csh_claim FOREIGN KEY (claim_id)
        REFERENCES "Claim" (claim_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_csh_stage FOREIGN KEY (stage_id)
        REFERENCES "ClaimStage" (stage_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_csh_user FOREIGN KEY (changed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "DeliveryStatusHistory" (
    history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id         INT          NOT NULL,
    status_id           INT          NOT NULL,
    changed_by_user_id  INT          NULL,
    changed_at          TIMESTAMP    NOT NULL,
    note                VARCHAR(300) NULL,
    CONSTRAINT uq_dsh_event UNIQUE (delivery_id, status_id, changed_at),
    CONSTRAINT fk_dsh_delivery FOREIGN KEY (delivery_id)
        REFERENCES "Delivery" (delivery_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dsh_status FOREIGN KEY (status_id)
        REFERENCES "DeliveryStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dsh_user FOREIGN KEY (changed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "InvoiceStatusHistory" (
    history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          INT          NOT NULL,
    status_id           INT          NOT NULL,
    changed_by_user_id  INT          NULL,
    changed_at          TIMESTAMP    NOT NULL,
    note                VARCHAR(300) NULL,
    CONSTRAINT uq_ish_event UNIQUE (invoice_id, status_id, changed_at),
    CONSTRAINT fk_ish_invoice FOREIGN KEY (invoice_id)
        REFERENCES "SalesInvoice" (invoice_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ish_status FOREIGN KEY (status_id)
        REFERENCES "InvoiceStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ish_user FOREIGN KEY (changed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE "CollectionStatusHistory" (
    history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id       INT          NOT NULL,
    status_id           INT          NOT NULL,
    changed_by_user_id  INT          NULL,
    changed_at          TIMESTAMP    NOT NULL,
    note                VARCHAR(300) NULL,
    CONSTRAINT uq_clsh_event UNIQUE (collection_id, status_id, changed_at),
    CONSTRAINT fk_clsh_collection FOREIGN KEY (collection_id)
        REFERENCES "Collection" (collection_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_clsh_status FOREIGN KEY (status_id)
        REFERENCES "CollectionStatus" (status_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_clsh_user FOREIGN KEY (changed_by_user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
);

/* The same shape extends to PurchaseOrder, StockTransfer, GoodsReceipt and
   JournalEntry whenever you want their trails: copy one of the five above,
   swap the document and the status lookup. */


/* ---------------------------------------------------------------------------
   PATTERN B -- one table for everything  (the alternative, for comparison)

   Cheaper to add: one table covers every document, present and future. The
   price is that document_id can point at nothing, and status_key is loose
   text rather than a foreign key. Use it only if the table count of Pattern A
   is genuinely a problem for you.
   --------------------------------------------------------------------------- */

-- CREATE TABLE "DocumentStatusHistory" (
--     history_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     document_type       VARCHAR(30)  NOT NULL,   -- 'SalesOrder', 'Claim', ...
--     document_id         INT          NOT NULL,   -- NOT a foreign key. That is the cost.
--     status_key          VARCHAR(25)  NOT NULL,   -- 'DISPATCHED', 'SENT', ...
--     changed_by_user_id  INT          NULL,
--     changed_at          TIMESTAMP    NOT NULL,
--     note                VARCHAR(300) NULL,
--     CONSTRAINT uq_dsh2_event UNIQUE (document_type, document_id, status_key, changed_at),
--     CONSTRAINT fk_dsh2_user FOREIGN KEY (changed_by_user_id)
--         REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE SET NULL
-- );
--
-- Nothing stops a row saying document_type = 'SalesOrder', document_id = 99999
-- for an order that never existed, and deleting an order leaves its trail
-- behind as garbage. Pattern A is worth the extra tables.


/* ---------------------------------------------------------------------------
   SAMPLE DATA -- the trail behind ORD-26-0142, the order on the dashboard
   --------------------------------------------------------------------------- */

INSERT INTO "OrderStatusHistory" (order_id, status_id, changed_by_user_id, changed_at, note) VALUES
    (1, 1,  7, '2026-08-13 09:12:00', 'Taken at the shop by the rep'),
    (1, 2,  7, '2026-08-13 09:40:00', 'Submitted to the order department'),
    (1, 4,  4, '2026-08-13 10:05:00', 'Within limit - confirmed'),
    (1, 6,  5, '2026-08-13 11:20:00', 'Picked from the Order Department shelf'),
    (1, 7,  4, '2026-08-13 11:42:00', 'Handed to the rep on the evening round');

INSERT INTO "ClaimStageHistory" (claim_id, stage_id, changed_by_user_id, changed_at, note) VALUES
    (4, 1, 6, '2026-08-04 10:30:00', 'Taken in from Mobile Zone Lahore'),
    (4, 2, 6, '2026-08-06 15:00:00', 'Batched and sent to China Mobile Plaza'),
    (7, 1, 6, '2026-07-20 11:00:00', 'Taken in from Saddar Mobile Plaza'),
    (7, 2, 6, '2026-07-22 16:20:00', 'Sent to the supplier'),
    (7, 3, 6, '2026-08-02 12:00:00', 'Fresh carton received back');

INSERT INTO "DeliveryStatusHistory" (delivery_id, status_id, changed_by_user_id, changed_at, note) VALUES
    (7, 2, 4, '2026-08-06 12:00:00', 'Booked with Pak International Cargo'),
    (7, 3, 4, '2026-08-06 17:30:00', 'Left the premises, nobody has confirmed'),
    (7, 4, 4, '2026-08-11 10:15:00', 'Rang the customer - shop was closed, re-attempting'),
    (6, 2, 4, '2026-08-09 11:00:00', 'Booked with Mehran Railway Cargo'),
    (6, 6, 4, '2026-08-12 14:40:00', 'Customer confirmed on the phone');


/* ---------------------------------------------------------------------------
   WHAT THE TRAIL BUYS YOU
   --------------------------------------------------------------------------- */

/* 1. The trail for one order, in order. */
-- SELECT s.status_name, h.changed_at, u.full_name, h.note
-- FROM "OrderStatusHistory" h
-- JOIN "OrderStatus" s ON s.status_id = h.status_id
-- LEFT JOIN "User" u ON u.user_id = h.changed_by_user_id
-- WHERE h.order_id = 1
-- ORDER BY h.changed_at;

/* 2. Who marked it dispatched, and when. Your exact question. */
-- SELECT o.order_no, u.full_name, h.changed_at
-- FROM "OrderStatusHistory" h
-- JOIN "SalesOrder" o  ON o.order_id = h.order_id
-- JOIN "OrderStatus" s ON s.status_id = h.status_id
-- LEFT JOIN "User" u   ON u.user_id = h.changed_by_user_id
-- WHERE s.status_key = 'DISPATCHED';

/* 3. How long each order sat in each status -- where the days actually go.
      This is the report you cannot write without the history table. */
-- SELECT o.order_no, s.status_name, h.changed_at,
--        LEAD(h.changed_at) OVER (PARTITION BY h.order_id ORDER BY h.changed_at)
--          - h.changed_at AS time_in_status
-- FROM "OrderStatusHistory" h
-- JOIN "SalesOrder" o  ON o.order_id = h.order_id
-- JOIN "OrderStatus" s ON s.status_id = h.status_id
-- ORDER BY o.order_no, h.changed_at;

/* 4. Average hours from packed to dispatched, over everything. */
-- SELECT AVG(d.changed_at - p.changed_at) AS avg_pack_to_dispatch
-- FROM "OrderStatusHistory" p
-- JOIN "OrderStatus" ps ON ps.status_id = p.status_id AND ps.status_key = 'PACKED'
-- JOIN "OrderStatusHistory" d ON d.order_id = p.order_id
-- JOIN "OrderStatus" ds ON ds.status_id = d.status_id AND ds.status_key = 'DISPATCHED';

/* 5. Claims the supplier has been sitting on, by how long -- the reminder the
      owner actually wants. */
-- SELECT c.claim_no, h.changed_at AS sent_on, NOW() - h.changed_at AS waiting
-- FROM "ClaimStageHistory" h
-- JOIN "Claim" c ON c.claim_id = h.claim_id
-- JOIN "ClaimStage" s ON s.stage_id = h.stage_id AND s.stage_key = 'SENT'
-- WHERE c.stage_id = 2
-- ORDER BY h.changed_at;


/* ---------------------------------------------------------------------------
   IF YOU ADD THIS LATER, BACKFILL FIRST

   Existing documents have a current status and no trail. One INSERT ... SELECT
   per table gives every one of them an opening row, so the reports above do
   not have to special-case rows that predate the feature:

     INSERT INTO "OrderStatusHistory"
            (order_id, status_id, changed_by_user_id, changed_at, note)
     SELECT order_id, status_id, created_by_user_id, order_date::timestamp,
            'Backfilled from the current status'
     FROM "SalesOrder";

   Remember to add the matching line to 03_sequence_reset.sql for each new
   table, so the identity sequences start above the seeded ids.
   =========================================================================== */
