/* ===========================================================================
   ADVANCE POS SYSTEM (AdvPOS) -- authentication additions
   ---------------------------------------------------------------------------
   Run this AFTER 01_schema.sql / 02_seed.sql / 03_sequence_reset.sql.

   Two things the login and forgot-password flows need that the original
   schema had no reason to carry:

     1. A place to keep a password-reset code.
     2. Real BCrypt password hashes on the staff rows, so people can sign in.

   Everything else already exists: "Role" carries role_key and home_path, and
   "User".password_hash was there from the start.
   =========================================================================== */

/* ---------------------------------------------------------------------------
   The reset code. We store a BCRYPT HASH of the six digits, never the digits
   themselves -- a leaked table must not hand somebody a working code.

   attempts is what stops a six-digit code being brute forced: the endpoint
   refuses the code once it hits 5, and the row is dead.
   --------------------------------------------------------------------------- */
CREATE TABLE "PasswordResetCode" (
    reset_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT          NOT NULL,
    code_hash    VARCHAR(200) NOT NULL,
    expires_at   TIMESTAMP    NOT NULL,
    consumed_at  TIMESTAMP    NULL,
    attempts     SMALLINT     NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_prc_user FOREIGN KEY (user_id)
        REFERENCES "User" (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

/* ---------------------------------------------------------------------------
   Sign-in credentials for the staff accounts.

   These are BCrypt hashes (work factor 11). The plain passwords are listed
   beside each one because this is a development seed and you need them to log
   in and check each panel. Change them in production -- Setup > Users, or by
   re-running this file with hashes of your own.
   --------------------------------------------------------------------------- */

-- admin@advpos.pk       Admin@1234
UPDATE "User" SET password_hash = '$2a$11$AWgWJx0rFP3N7gDbmgnYEegJaXUyfsNdVxcAo.gpt8DnH.Es73JMG'
WHERE email = 'admin@advpos.pk';

-- accounts@advpos.pk    Accounts@1234
UPDATE "User" SET password_hash = '$2a$11$.1zBr29CWX0SU3fsCJf4du2XCG54CSf/Uc53Vv7fLNhFti6.jBDmq'
WHERE email = 'accounts@advpos.pk';

-- order@advpos.pk       Order@1234
UPDATE "User" SET password_hash = '$2a$11$qYHtuGfcnEX1D32.JTusLu7sRB8/x66OQJVB6ElqIZJltz2DVXPsC'
WHERE email = 'order@advpos.pk';

-- sales@advpos.pk       Sales@1234
UPDATE "User" SET password_hash = '$2a$11$ysOAkBN8aPFi1KaGl4CUV.UJkakBjtpfeTvQkUDKBTqHPaq4/qNqe'
WHERE email = 'sales@advpos.pk';

-- every other staff account            Vizo@1234
UPDATE "User" SET password_hash = '$2a$11$XYhhNi68wR4dlC/H4w5ay.v/9QsmSUgi7LDKK53JQhgoIBiQDmUD.'
WHERE email IN ('nadia@vizo.com.pk', 'junaid@vizo.com.pk', 'ahmed@vizo.com.pk',
                'imran@vizo.com.pk', 'sara@vizo.com.pk', 'asad@vizo.com.pk',
                'system@advpos.pk');
