/* ===========================================================================
   AdvPOS -- authentication additions for the NEON database (PascalCase)
   ---------------------------------------------------------------------------
   The Neon database uses PascalCase column names, so 05_auth.sql (snake_case)
   does not apply to it. This is the same change expressed for Neon.

   Idempotent: safe to run more than once.
   =========================================================================== */

/* 1. The reset-code table. AuthController's forgot-password flow needs it;
      without it every /auth/forgot-password call throws 42P01.
      A BCrypt HASH of the six digits is stored, never the digits. */
CREATE TABLE IF NOT EXISTS "PasswordResetCode" (
    "ResetId"    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     INT          NOT NULL,
    "CodeHash"   VARCHAR(200) NOT NULL,
    "ExpiresAt"  TIMESTAMP    NOT NULL,
    "ConsumedAt" TIMESTAMP    NULL,
    "Attempts"   SMALLINT     NOT NULL DEFAULT 0 CHECK ("Attempts" >= 0),
    "CreatedAt"  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_prc_user FOREIGN KEY ("UserId")
        REFERENCES "User" ("UserId") ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "ix_prc_user" ON "PasswordResetCode" ("UserId");

/* 2. Real BCrypt hashes (work factor 11) on the staff rows.
      Rows 2-11 still carry the literal string
      '$2b$12$PLACEHOLDER.REPLACE.ON.FIRST.LOGIN.aaaa...' from 02_seed.sql,
      which is not a valid BCrypt hash -- those accounts cannot sign in at all.
      Only rows whose hash is still the placeholder are touched. */

-- admin@advpos.pk       Admin@1234
UPDATE "User" SET "PasswordHash" = '$2a$11$AWgWJx0rFP3N7gDbmgnYEegJaXUyfsNdVxcAo.gpt8DnH.Es73JMG'
WHERE "Email" = 'admin@advpos.pk' AND "PasswordHash" LIKE '$2b$12$PLACEHOLDER%';

-- accounts@advpos.pk    Accounts@1234
UPDATE "User" SET "PasswordHash" = '$2a$11$.1zBr29CWX0SU3fsCJf4du2XCG54CSf/Uc53Vv7fLNhFti6.jBDmq'
WHERE "Email" = 'accounts@advpos.pk' AND "PasswordHash" LIKE '$2b$12$PLACEHOLDER%';

-- order@advpos.pk       Order@1234
UPDATE "User" SET "PasswordHash" = '$2a$11$qYHtuGfcnEX1D32.JTusLu7sRB8/x66OQJVB6ElqIZJltz2DVXPsC'
WHERE "Email" = 'order@advpos.pk' AND "PasswordHash" LIKE '$2b$12$PLACEHOLDER%';

-- sales@advpos.pk       Sales@1234
UPDATE "User" SET "PasswordHash" = '$2a$11$ysOAkBN8aPFi1KaGl4CUV.UJkakBjtpfeTvQkUDKBTqHPaq4/qNqe'
WHERE "Email" = 'sales@advpos.pk' AND "PasswordHash" LIKE '$2b$12$PLACEHOLDER%';

-- every other staff account            Vizo@1234
UPDATE "User" SET "PasswordHash" = '$2a$11$XYhhNi68wR4dlC/H4w5ay.v/9QsmSUgi7LDKK53JQhgoIBiQDmUD.'
WHERE "Email" IN ('nadia@vizo.com.pk', 'junaid@vizo.com.pk', 'ahmed@vizo.com.pk',
                  'imran@vizo.com.pk', 'sara@vizo.com.pk', 'asad@vizo.com.pk',
                  'system@advpos.pk')
  AND "PasswordHash" LIKE '$2b$12$PLACEHOLDER%';
