-- ═══════════════════════════════════════════════════════════════════════════
--  10_document_files.sql
--
--  One table recording every PDF this system generates and where it went.
--
--  WHY A TABLE RATHER THAN A COLUMN PER DOCUMENT. 08_sales_documents.sql put
--  "PdfUrl" straight on "SalesInvoice", which is right for the bill -- it is
--  part of that row's identity. Doing the same for the other eleven printable
--  documents would mean eleven schema changes, eleven scaffolded models to
--  patch, and eleven places to look when somebody asks where a PDF is.
--
--  It also would not work for REPORTS. A sales summary for August has no row
--  anywhere to hang a column off; it is a document about a date range, and the
--  same report re-run tomorrow is a different file.
--
--  So: one row per generated file, keyed by (DocKind, DocKey). DocKey is the
--  document's own id for a document, or a parameter fingerprint for a report --
--  "2026-08-01:2026-08-31:1" -- so re-running the same report replaces its file
--  rather than piling up copies.
--
--  EVERY FILE GOES TO THE "CloudinaryPdfs" ACCOUNT in appsettings.json. Nothing
--  is written to disk anywhere in this project, deliberately: the API runs on a
--  host whose filesystem is not backed up and may be replaced, and a bill that
--  only exists next to the binary is a bill that is one deploy from gone.
--
--  Idempotent. ROLLBACK is at the foot of the file.
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS "DocumentFile" (
    "FileId"          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- what kind of document: purchase.order, stock.transfer, report.aging.customer …
    "DocKind"         varchar(40)  NOT NULL,

    -- the document's own id, or a parameter fingerprint for a report
    "DocKey"          varchar(120) NOT NULL,

    -- the human-readable number, when the document has one (PO-26-0042)
    "DocNo"           varchar(60),

    -- what the file is called and where it now lives
    "FileName"        varchar(160) NOT NULL,
    "PdfUrl"          varchar(500) NOT NULL,
    "PdfPublicId"     varchar(255) NOT NULL,
    "Bytes"           bigint       NOT NULL DEFAULT 0,

    -- whether the store will actually SERVE it. Cloudinary blocks PDF delivery
    -- by default on accounts created since 2023: the upload succeeds and every
    -- request to the URL answers 401. Recorded so the app knows whether that
    -- link is safe to give a customer.
    "IsDeliverable"   boolean      NOT NULL DEFAULT false,

    "GeneratedByUserId" int        NOT NULL,
    "GeneratedAt"     timestamp without time zone NOT NULL,

    CONSTRAINT "FK_DocumentFile_User"
        FOREIGN KEY ("GeneratedByUserId") REFERENCES "User" ("UserId")
);

/* One current file per document. Re-generating REPLACES the row, so the table
   stays the size of the document set rather than growing with every click. */
CREATE UNIQUE INDEX IF NOT EXISTS "UX_DocumentFile_Doc"
    ON "DocumentFile" ("DocKind", "DocKey");

CREATE INDEX IF NOT EXISTS "IX_DocumentFile_Generated"
    ON "DocumentFile" ("GeneratedAt" DESC);

COMMENT ON TABLE "DocumentFile" IS
  'Every PDF the API has generated, and its Cloudinary link. Nothing is stored
   on the API host filesystem -- see the header of 10_document_files.sql.';

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
--  ROLLBACK
--    DROP INDEX IF EXISTS "IX_DocumentFile_Generated";
--    DROP INDEX IF EXISTS "UX_DocumentFile_Doc";
--    DROP TABLE IF EXISTS "DocumentFile";
-- ═══════════════════════════════════════════════════════════════════════════
