/* ═══════════════════════════════════════════════════════════════════════════
   31 — A LEDGER FOR EVERY MEMBER OF STAFF, INCLUDING THE ONES WHO NEVER SIGN IN
   ═══════════════════════════════════════════════════════════════════════════

   Applied to the local test copy only — NOT yet run on live.
   Idempotent: tables and columns are created IF NOT EXISTS, seeds are guarded.

   The owner, 26 September: "a staff ledger for every staff member" -- the
   people with a login, AND the drivers and helpers who have none -- with a
   staff category (Salesman, Driver, Office ...) asked for when the account is
   opened, and salary, advances and deductions posting to the main books.

   ───────────────────── WHY A TABLE OF ITS OWN, NOT "User" ────────────────────

   Everybody on the payroll today is a "User" with an "Employee" row, and every
   "User" row belongs to a ROLE that decides what they may sign in to. A driver
   has no role in this system and must never be able to sign in -- and "User"
   cannot hold such a person cleanly:

     · "RoleId" is NOT NULL, and every role in "Role" opens some screen. A
       fifth, empty role would be one ticked box in Setup > Roles away from
       giving a van driver the Order Department's permissions.
     · The sign-in code (Talha's AuthController, which this branch may not
       touch) reads "User" directly; keeping non-users OUT of that table is the
       only way to be certain nothing in it can ever let one in.
     · "Employee" rows are referenced by eighteen foreign keys (orders, stock
       adjustments, collections ...) that all mean "a person who DID something
       in the system". A driver never does.

   So "StaffMember" is the payroll list. A person who also signs in is linked
   through "UserId" (unique, nullable); a person who does not simply has none,
   and there is nothing to sign in WITH -- no email, no password, no role.
   Giving a driver a login later is Setup > Users as usual, then linking the
   two on the staff screen.

   ─────────────────────────── THE SUBLEDGER ──────────────────────────────────

   "JournalEntryLine"."StaffId" says which member of staff a line on 2140 Staff
   Payables belongs to -- the same shape as "PartyUserId" for a customer's line
   on 1130. Nullable, ON DELETE SET NULL like the party column; the screen
   refuses to delete anybody with a line against them anyway.

   ─────────────────────────────── BACKFILL ────────────────────────────────────

   Every existing "Employee" gets a "StaffMember" row, linked, with a category
   from their role (sales -> Salesman, order-dept -> Order Desk, accountant ->
   Office, super-admin -> Management). EMP-000, the system service account, is
   not a person and is left out. New logins created after this migration get
   their row the first time the Staff Ledgers screen is opened
   (StaffLedgerController.EnsureStaffRows), so nobody on the payroll can be
   missing from it.

   ═══════════════════════════════════════════════════════════════════════════ */

BEGIN;

CREATE TABLE IF NOT EXISTS "StaffCategory" (
    "StaffCategoryId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryName"    varchar(60) NOT NULL,
    CONSTRAINT "UX_StaffCategory_Name" UNIQUE ("CategoryName")
);

CREATE TABLE IF NOT EXISTS "StaffMember" (
    "StaffId"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StaffCode"       varchar(20)  NOT NULL,
    "FullName"        varchar(120) NOT NULL,
    "Phone"           varchar(30),
    "Cnic"            varchar(20),
    "StaffCategoryId" integer      NOT NULL REFERENCES "StaffCategory"("StaffCategoryId"),
    "UserId"          integer      REFERENCES "User"("UserId") ON DELETE SET NULL,
    "MonthlySalary"   numeric(14,2) NOT NULL DEFAULT 0,
    /* What was owed to them (positive) or by them (negative, an advance) on
       the day this ledger started -- the staff equivalent of
       "Party"."OpeningBalance", in the account's own natural (credit) sense. */
    "OpeningBalance"  numeric(14,2) NOT NULL DEFAULT 0,
    "JoinedOn"        date         NOT NULL DEFAULT CURRENT_DATE,
    "IsActive"        boolean      NOT NULL DEFAULT true,
    "Notes"           varchar(300),
    "CreatedAt"       timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "UX_StaffMember_Code" UNIQUE ("StaffCode"),
    CONSTRAINT "UX_StaffMember_User" UNIQUE ("UserId"),
    CONSTRAINT "CK_StaffMember_Salary" CHECK ("MonthlySalary" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_StaffMember_Category" ON "StaffMember" ("StaffCategoryId");

ALTER TABLE "JournalEntryLine" ADD COLUMN IF NOT EXISTS "StaffId" integer;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_JournalEntryLine_Staff') THEN
        ALTER TABLE "JournalEntryLine"
            ADD CONSTRAINT "FK_JournalEntryLine_Staff"
            FOREIGN KEY ("StaffId") REFERENCES "StaffMember"("StaffId") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_JournalEntryLine_Staff" ON "JournalEntryLine" ("StaffId")
    WHERE "StaffId" IS NOT NULL;

/* The customer ledger reads a party's lines on every page of the index; the
   column had no index of its own. */
CREATE INDEX IF NOT EXISTS "IX_JournalEntryLine_Party" ON "JournalEntryLine" ("PartyUserId")
    WHERE "PartyUserId" IS NOT NULL;

/* ── categories ─────────────────────────────────────────────────────────── */
INSERT INTO "StaffCategory" ("CategoryName")
SELECT n FROM unnest(ARRAY['Salesman','Order Desk','Office','Driver','Helper','Management']) AS n
WHERE NOT EXISTS (SELECT 1 FROM "StaffCategory" c WHERE c."CategoryName" = n);

/* ── every existing employee, linked ────────────────────────────────────── */
INSERT INTO "StaffMember" ("StaffCode", "FullName", "Phone", "StaffCategoryId", "UserId",
                           "JoinedOn", "IsActive")
SELECT e."EmployeeCode", u."FullName", u."Phone",
       (SELECT c."StaffCategoryId" FROM "StaffCategory" c WHERE c."CategoryName" =
            CASE r."RoleKey" WHEN 'sales' THEN 'Salesman'
                             WHEN 'order-dept' THEN 'Order Desk'
                             WHEN 'accountant' THEN 'Office'
                             ELSE 'Management' END),
       u."UserId", e."JoinedOn", u."IsActive"
  FROM "Employee" e
  JOIN "User" u ON u."UserId" = e."UserId"
  JOIN "Role" r ON r."RoleId" = u."RoleId"
 WHERE e."EmployeeCode" <> 'EMP-000'
   AND NOT EXISTS (SELECT 1 FROM "StaffMember" s WHERE s."UserId" = u."UserId")
   AND NOT EXISTS (SELECT 1 FROM "StaffMember" s WHERE s."StaffCode" = e."EmployeeCode");

COMMIT;

/* ── rollback ────────────────────────────────────────────────────────────────
   ALTER TABLE "JournalEntryLine" DROP CONSTRAINT IF EXISTS "FK_JournalEntryLine_Staff";
   DROP INDEX IF EXISTS "IX_JournalEntryLine_Staff";
   ALTER TABLE "JournalEntryLine" DROP COLUMN IF EXISTS "StaffId";
   DROP TABLE IF EXISTS "StaffMember";
   DROP TABLE IF EXISTS "StaffCategory";
   (IX_JournalEntryLine_Party is harmless to keep.)
*/
