/* ═══════════════════════════════════════════════════════════════════════════
   32 — THE ITEM LINE ON A HAND-WRITTEN LEDGER ROW
   ═══════════════════════════════════════════════════════════════════════════

   Applied to the local test copy only — NOT yet run on live.
   Idempotent.

   The customer ledger has a "+" that adds a row by hand: date, description,
   and OPTIONALLY an item, a quantity and a price (amount = qty x price) --
   because in the old system that is how an adjustment for goods was written,
   and the statement prints it the same way it prints a sale, with the item
   indented beneath.

   The row is LEDGER-ONLY. It is a journal entry (Dr/Cr Accounts Receivable
   with the party on the line, the other side on an account the user picks)
   and nothing else: no invoice, no stock movement, no document number of its
   own. So the item cannot live on a sale-invoice line. It lives here, pointing
   at the journal entry it explains.

   "ProductId" is nullable: the item may be typed as free text ("Old stock
   adjustment") rather than picked from the catalogue. "ItemName" is what was
   shown when it was written, kept even if the product is renamed later -- the
   same reason an invoice line keeps its own price.

   ═══════════════════════════════════════════════════════════════════════════ */

BEGIN;

CREATE TABLE IF NOT EXISTS "LedgerEntryItem" (
    "LedgerEntryItemId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntryId"           integer       NOT NULL REFERENCES "JournalEntry"("EntryId") ON DELETE CASCADE,
    "LineNo"            smallint      NOT NULL DEFAULT 1,
    "ProductId"         integer       REFERENCES "Product"("ProductId") ON DELETE SET NULL,
    "ItemName"          varchar(200)  NOT NULL,
    "Qty"               numeric(12,2) NOT NULL,
    "Rate"              numeric(14,2) NOT NULL,
    "Amount"            numeric(14,2) NOT NULL,
    CONSTRAINT "CK_LedgerEntryItem_Qty" CHECK ("Qty" > 0),
    CONSTRAINT "CK_LedgerEntryItem_Rate" CHECK ("Rate" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_LedgerEntryItem_Entry" ON "LedgerEntryItem" ("EntryId");

COMMIT;

/* ── rollback ────────────────────────────────────────────────────────────────
   DROP TABLE IF EXISTS "LedgerEntryItem";
*/
