/* ═══════════════════════════════════════════════════════════════════════════
   35 — ONE EXPENSE SHEET PER DAY, PER LOCATION
   ═══════════════════════════════════════════════════════════════════════════

   Applied to the local test copy only — NOT yet run on live.

   The owner, 26 September (translated):

     "Expense records display fine today. But every expense gets its own
      invoice. We want ONE invoice per day holding all of that day's expenses.
      Open a date, get Excel-like input boxes, enter as many expenses as you
      like, and a Print button at the top generates that day's invoice."

   ─────────────────────────────── THE SHAPE ──────────────────────────────────

   "ExpenseSheet" is the day: one date, one location, one number (EXS-26-0001),
   one status, and -- once the accountant approves it -- ONE journal entry
   holding every line. The individual "Expense" rows stay exactly what they
   were (every report, the P&L drill-downs, the nightly insights and the AI
   summary read them) and gain a "SheetId" saying which day they belong to.

   Scoped by LOCATION as well as date because Shop 2 keeps its own cash and
   its own expense account: the shop's petty cash and the warehouse's are two
   different drawers, and one sheet mixing them would be one sheet nobody can
   count against a drawer.

   ─────────────────────────── WHY A PARTIAL INDEX ────────────────────────────

   "One sheet per date per location" is enforced by the database, but only
   among sheets that still stand. A sheet that has been REVERSED stays on file
   as history -- it was approved, it did reach the ledger, and it was undone --
   and the accountant must then be able to open that date again and enter the
   corrected day. Hence WHERE "ReversedAt" IS NULL.

   ────────────────────────── THE EXISTING EXPENSES ───────────────────────────

   Section 4 groups every expense that has no sheet yet by date + location and
   files each group under a new sheet, numbered in date order.

     · Nothing is re-posted. An expense that already has a journal entry keeps
       it; the sheet's own "EntryId" stays NULL for these, because no single
       entry was written for the day -- the screen lists the per-line entries
       instead.
     · A sheet is APPROVED (POSTED) when every live line on it was posted.
       Any line still in DRAFT makes the sheet a DRAFT, so the accountant can
       approve the rest of that day with the new button.
     · A sheet whose every line was reversed/rejected/cancelled is filed as
       REVERSED, with "ReversedAt" set, so it never blocks that date.

   On the 26 Sep copy of live that is 10 expenses into 9 sheets: 7 approved,
   2 draft (30 Apr / Karachi Order Department holds the one DRAFT SMS bill;
   30 Aug / Karachi Warehouse holds one DRAFT and one already-REVERSED line).

   Idempotent: every statement checks before it acts, and section 4 only
   touches expenses whose "SheetId" is still NULL.
   ═══════════════════════════════════════════════════════════════════════════ */

BEGIN;

/* ─────────────────────────── 1. THE SHEET TABLE ─────────────────────────── */

CREATE TABLE IF NOT EXISTS "ExpenseSheet" (
    "SheetId"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SheetNo"          varchar(20)  NOT NULL UNIQUE,
    "SheetDate"        date         NOT NULL,
    "LocationId"       integer      NOT NULL REFERENCES "Location"("LocationId") ON UPDATE CASCADE ON DELETE RESTRICT,
    "StatusId"         integer      NOT NULL REFERENCES "PostingStatus"("StatusId") ON UPDATE CASCADE ON DELETE RESTRICT,
    /* The ONE entry approval writes. NULL while draft, and NULL for a sheet
       made out of expenses that were posted one at a time before sheets
       existed (their entries hang off each "Expense" row instead). */
    "EntryId"          integer      NULL REFERENCES "JournalEntry"("EntryId") ON UPDATE CASCADE ON DELETE SET NULL,
    "Notes"            varchar(500) NULL,
    "CreatedByUserId"  integer      NOT NULL REFERENCES "User"("UserId") ON UPDATE CASCADE ON DELETE RESTRICT,
    "CreatedAt"        timestamp without time zone NOT NULL,
    "UpdatedAt"        timestamp without time zone NULL,
    "ApprovedByUserId" integer      NULL REFERENCES "User"("UserId") ON UPDATE CASCADE ON DELETE SET NULL,
    "ApprovedAt"       timestamp without time zone NULL,
    "ReversedByUserId" integer      NULL REFERENCES "User"("UserId") ON UPDATE CASCADE ON DELETE SET NULL,
    "ReversedAt"       timestamp without time zone NULL,
    "ReversalReason"   varchar(500) NULL
);

/* ON DELETE RESTRICT everywhere, on purpose (HANDOFF trap 24): every other
   foreign key into "Location" and "User" in this schema CASCADES, so deleting
   a location silently deletes its documents. A day of approved expenses is
   not something that should vanish because a location row was tidied up. */

CREATE UNIQUE INDEX IF NOT EXISTS "UX_ExpenseSheet_Day"
    ON "ExpenseSheet" ("SheetDate", "LocationId")
    WHERE "ReversedAt" IS NULL;

CREATE INDEX IF NOT EXISTS "IX_ExpenseSheet_SheetDate" ON "ExpenseSheet" ("SheetDate" DESC);

/* ─────────────────────── 2. EXPENSE KNOWS ITS SHEET ─────────────────────── */

ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "SheetId" integer NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_expense_sheet') THEN
        ALTER TABLE "Expense"
            ADD CONSTRAINT fk_expense_sheet FOREIGN KEY ("SheetId")
            REFERENCES "ExpenseSheet"("SheetId") ON UPDATE CASCADE ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_Expense_SheetId" ON "Expense" ("SheetId");

/* ───────────────────────── 3. THE NUMBER SERIES ─────────────────────────── */

/* HANDOFF trap 9: NextNumber() looks a series up by PREFIX and silently falls
   back to PREFIX-yyyyMMddHHmmss when it is missing -- so the row has to exist
   before the first sheet is opened, or the numbers look wrong days later.
   Shows up at Setup > Numbering like every other series. */
INSERT INTO "DocumentSeries" ("SeriesKey", "Label", "Prefix", "IncludeYear", "Padding", "NextNumber")
SELECT 'expense.sheet', 'Daily Expense Sheet', 'EXS', true, 4, 1
WHERE NOT EXISTS (SELECT 1 FROM "DocumentSeries" WHERE "Prefix" = 'EXS' OR "SeriesKey" = 'expense.sheet');

/* ─────────────────── 4. FILE THE EXISTING EXPENSES ──────────────────────── */

DO $$
DECLARE
    g          record;
    s_prefix   text;
    s_year     boolean;
    s_pad      int;
    n          int;
    new_id     int;
    st_draft   int := (SELECT "StatusId" FROM "PostingStatus" WHERE "StatusKey" = 'DRAFT');
    st_posted  int := (SELECT "StatusId" FROM "PostingStatus" WHERE "StatusKey" = 'POSTED');
    st_rev     int := (SELECT "StatusId" FROM "PostingStatus" WHERE "StatusKey" = 'REVERSED');
    sheet_st   int;
BEGIN
    SELECT "Prefix", "IncludeYear", "Padding", "NextNumber"
      INTO s_prefix, s_year, s_pad, n
      FROM "DocumentSeries" WHERE "Prefix" = 'EXS';

    FOR g IN
        SELECT e."ExpenseDate" AS d, e."LocationId" AS loc,
               count(*) FILTER (WHERE ps."StatusKey" = 'DRAFT')  AS drafts,
               count(*) FILTER (WHERE ps."StatusKey" = 'POSTED') AS posted,
               min(e."CreatedByUserId")                          AS created_by,
               /* whoever posted the earliest line stands in as the approver */
               (SELECT je."PostedByUserId" FROM "Expense" x
                  JOIN "JournalEntry" je ON je."EntryId" = x."EntryId"
                 WHERE x."ExpenseDate" = e."ExpenseDate" AND x."LocationId" = e."LocationId"
                 ORDER BY x."ExpenseId" LIMIT 1)                 AS approved_by,
               (SELECT je."CreatedAt" FROM "Expense" x
                  JOIN "JournalEntry" je ON je."EntryId" = x."EntryId"
                 WHERE x."ExpenseDate" = e."ExpenseDate" AND x."LocationId" = e."LocationId"
                 ORDER BY x."ExpenseId" LIMIT 1)                 AS approved_on
          FROM "Expense" e
          JOIN "PostingStatus" ps ON ps."StatusId" = e."StatusId"
         WHERE e."SheetId" IS NULL
         GROUP BY e."ExpenseDate", e."LocationId"
         ORDER BY e."ExpenseDate", e."LocationId"
    LOOP
        /* A standing sheet for that day may already exist (the migration was
           re-run after somebody opened one): file the stragglers under it. */
        SELECT "SheetId" INTO new_id FROM "ExpenseSheet"
         WHERE "SheetDate" = g.d AND "LocationId" = g.loc AND "ReversedAt" IS NULL;

        IF new_id IS NULL THEN
            sheet_st := CASE
                WHEN g.drafts > 0 THEN st_draft
                WHEN g.posted > 0 THEN st_posted
                ELSE st_rev
            END;

            INSERT INTO "ExpenseSheet" (
                "SheetNo", "SheetDate", "LocationId", "StatusId", "EntryId", "Notes",
                "CreatedByUserId", "CreatedAt",
                "ApprovedByUserId", "ApprovedAt",
                "ReversedByUserId", "ReversedAt", "ReversalReason")
            VALUES (
                s_prefix || '-'
                    || CASE WHEN s_year THEN to_char(g.d, 'YY') || '-' ELSE '' END
                    || lpad(n::text, s_pad, '0'),
                g.d, g.loc, sheet_st, NULL,
                'Filed by migration 35 from expenses entered one at a time before day sheets existed.',
                g.created_by, g.d::timestamp,
                CASE WHEN sheet_st = st_posted THEN g.approved_by END,
                CASE WHEN sheet_st = st_posted THEN g.approved_on::timestamp END,
                NULL,
                CASE WHEN sheet_st = st_rev THEN now()::timestamp END,
                CASE WHEN sheet_st = st_rev THEN 'Every line was reversed or rejected before day sheets existed.' END)
            RETURNING "SheetId" INTO new_id;

            n := n + 1;
        END IF;

        UPDATE "Expense" SET "SheetId" = new_id
         WHERE "SheetId" IS NULL AND "ExpenseDate" = g.d AND "LocationId" = g.loc;
    END LOOP;

    /* Trap 10: a counter parked behind the data throws 23505 on the FIRST
       insert. Wind it past the highest number actually used, whatever the
       year segment says. */
    UPDATE "DocumentSeries"
       SET "NextNumber" = GREATEST("NextNumber", n,
             COALESCE((SELECT max(substring("SheetNo" from '(\d+)$')::int) + 1 FROM "ExpenseSheet"), 1))
     WHERE "Prefix" = 'EXS';
END $$;

/* ──────────────────────────── 5. VERIFY ─────────────────────────────────── */

DO $$
DECLARE orphans int;
BEGIN
    SELECT count(*) INTO orphans FROM "Expense" WHERE "SheetId" IS NULL;
    IF orphans > 0 THEN
        RAISE EXCEPTION '% expense(s) still have no sheet', orphans;
    END IF;
END $$;

COMMIT;

/* What it did -- run after COMMIT:

   SELECT s."SheetNo", s."SheetDate", l."LocationName", ps."StatusKey",
          count(e.*) AS lines, sum(e."Amount") AS total
     FROM "ExpenseSheet" s
     JOIN "Location" l ON l."LocationId" = s."LocationId"
     JOIN "PostingStatus" ps ON ps."StatusId" = s."StatusId"
     LEFT JOIN "Expense" e ON e."SheetId" = s."SheetId"
    GROUP BY 1,2,3,4 ORDER BY 2;

   ROLLBACK (only before any sheet has been approved through the new screen):

   BEGIN;
   ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS fk_expense_sheet;
   ALTER TABLE "Expense" DROP COLUMN IF EXISTS "SheetId";
   DROP TABLE IF EXISTS "ExpenseSheet";
   DELETE FROM "DocumentSeries" WHERE "Prefix" = 'EXS';
   COMMIT;
*/
